### ISSUE TITLE
您好，我看了您“i3wm切换布局工具

### ISSUE THREAD

**Issue by thaoeu** [EvanMeek/evanmeek.github.io#7]

**Comment by thaoeu** [comment]
有些问题想请教，我使用i3-instant-layout 工具切换成类dwm布局后并不能持久化，再次打开一个新的窗口还是按i3原来的规则呈现，请问是否能保持类dwm的布局，让新窗口始终居左。

**Comment by EvanMeek** [comment]
> 有些问题想请教，我使用i3-instant-layout 工具切换成类dwm布局后并不能持久化，再次打开一个新的窗口还是按i3原来的规则呈现，请问是否能保持类dwm的布局，让新窗口始终居左。

没折腾过，不过应该可以去找找其他的使用

**Comment by EvanMeek** [comment]
> 有些问题想请教，我使用i3-instant-layout 工具切换成类dwm布局后并不能持久化，再次打开一个新的窗口还是按i3原来的规则呈现，请问是否能保持类dwm的布局，让新窗口始终居左。

可以使用 https://github.com/nwg-piotr/autotiling
